package UserInterface;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class TCHormigueroFrame extends javax.swing.JFrame {
    public static String tcCedula = "210065415-7"; 
    public static String tcNombre = "Carlos Adriel Troya Romero";
    public String genoAlimento = "<GenoAlimento>";
    public String ingestaNativa = "<IngestaNativa>";
    /**
     * Creates new form TCHormigueroFrame
     */
    
    int xMouse;
    int yMouse; 
    public TCHormigueroFrame() {
        initComponents();
        requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tcFondoPanel = new javax.swing.JPanel();
        tcBarraTituloPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tcTituloLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tcInfoPersonalPnl = new javax.swing.JPanel();
        tcNombreLbl = new javax.swing.JLabel();
        tcCedulaLbl = new javax.swing.JLabel();
        tcNombreTxtBox = new javax.swing.JTextField();
        tcCedulaTxtBox = new javax.swing.JTextField();
        tcLogoImgLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tcAlimentarNBtn = new java.awt.Button();
        tcGenoalimentoCB = new javax.swing.JComboBox<>();
        tcIngestaNativaCB = new javax.swing.JComboBox<>();
        tcaAlimentarGBtn = new java.awt.Button();
        tcBotonesPnl = new javax.swing.JPanel();
        tcGuardarBtn = new java.awt.Button();
        tcEliminarBtn1 = new java.awt.Button();
        tcCrearBtn1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tcFondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        tcFondoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tcFondoPanel.setMinimumSize(new java.awt.Dimension(600, 500));
        tcFondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tcBarraTituloPanel.setBackground(new java.awt.Color(255, 255, 255));
        tcBarraTituloPanel.setAlignmentX(0.5F);
        tcBarraTituloPanel.setAlignmentY(0.5F);
        tcBarraTituloPanel.setAutoscrolls(true);
        tcBarraTituloPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tcBarraTituloPanelMouseDragged(evt);
            }
        });
        tcBarraTituloPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tcBarraTituloPanelMousePressed(evt);
            }
        });

        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tcTituloLabel.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        tcTituloLabel.setForeground(new java.awt.Color(102, 102, 102));
        tcTituloLabel.setText("EcuaFauna 2k24A");

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tcBarraTituloPanelLayout = new javax.swing.GroupLayout(tcBarraTituloPanel);
        tcBarraTituloPanel.setLayout(tcBarraTituloPanelLayout);
        tcBarraTituloPanelLayout.setHorizontalGroup(
            tcBarraTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tcBarraTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tcTituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tcBarraTituloPanelLayout.setVerticalGroup(
            tcBarraTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tcBarraTituloPanelLayout.createSequentialGroup()
                .addGroup(tcBarraTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tcTituloLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        tcFondoPanel.add(tcBarraTituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 30));
        tcFondoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 10));

        tcInfoPersonalPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tcNombreLbl.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tcNombreLbl.setText("Nombres:");
        tcInfoPersonalPnl.add(tcNombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 20));

        tcCedulaLbl.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tcCedulaLbl.setText("Cedula:");
        tcInfoPersonalPnl.add(tcCedulaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 20));

        tcNombreTxtBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tcNombreTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tcNombreTxtBox.setText(tcNombre);
        tcInfoPersonalPnl.add(tcNombreTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 240, -1));

        tcCedulaTxtBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tcCedulaTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tcCedulaTxtBox.setText(tcCedula);
        tcCedulaTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcCedulaTxtBoxActionPerformed(evt);
            }
        });
        tcInfoPersonalPnl.add(tcCedulaTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 240, -1));

        tcFondoPanel.add(tcInfoPersonalPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 520, 80));

        tcLogoImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tcHomigaLogo.png"))); // NOI18N
        tcFondoPanel.add(tcLogoImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        tcFondoPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 510, 80));

        tcAlimentarNBtn.setBackground(new java.awt.Color(102, 102, 102));
        tcAlimentarNBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tcAlimentarNBtn.setForeground(new java.awt.Color(224, 224, 224));
        tcAlimentarNBtn.setLabel("alimentar con Ingesta Nativa\n");
        tcAlimentarNBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcAlimentarNBtnActionPerformed(evt);
            }
        });
        tcFondoPanel.add(tcAlimentarNBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 230, 30));

        tcGenoalimentoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "XX", "XY" }));
        tcFondoPanel.add(tcGenoalimentoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 250, 30));

        tcIngestaNativaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnívoro", "Herbívoro", "Omnívoro", "Insectívoro", "Nectarívaro" }));
        tcFondoPanel.add(tcIngestaNativaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 250, 30));

        tcaAlimentarGBtn.setBackground(new java.awt.Color(102, 102, 102));
        tcaAlimentarGBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tcaAlimentarGBtn.setForeground(new java.awt.Color(224, 224, 224));
        tcaAlimentarGBtn.setLabel("alimentar con Genoalimento\n");
        tcaAlimentarGBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcaAlimentarGBtnActionPerformed(evt);
            }
        });
        tcFondoPanel.add(tcaAlimentarGBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 230, 30));

        tcBotonesPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tcGuardarBtn.setBackground(new java.awt.Color(196, 218, 249));
        tcGuardarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tcGuardarBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tcGuardarBtn.setForeground(new java.awt.Color(51, 51, 51));
        tcGuardarBtn.setLabel("Guardar");
        tcGuardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcGuardarBtnActionPerformed(evt);
            }
        });
        tcBotonesPnl.add(tcGuardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 30));
        tcGuardarBtn.getAccessibleContext().setAccessibleName("Guardar");

        tcEliminarBtn1.setBackground(new java.awt.Color(196, 218, 249));
        tcEliminarBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tcEliminarBtn1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tcEliminarBtn1.setForeground(new java.awt.Color(51, 51, 51));
        tcEliminarBtn1.setLabel("Eliminar");
        tcEliminarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcEliminarBtn1ActionPerformed(evt);
            }
        });
        tcBotonesPnl.add(tcEliminarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 30));

        tcFondoPanel.add(tcBotonesPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 510, 70));

        tcCrearBtn1.setBackground(new java.awt.Color(102, 102, 102));
        tcCrearBtn1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tcCrearBtn1.setForeground(new java.awt.Color(224, 224, 224));
        tcCrearBtn1.setLabel("crear hormiga larva\n");
        tcCrearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcCrearBtn1ActionPerformed(evt);
            }
        });
        tcFondoPanel.add(tcCrearBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 230, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Hormiguero Virtual");
        tcFondoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 130, 30));

        getContentPane().add(tcFondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>                        

    private void tcBarraTituloPanelMousePressed(java.awt.event.MouseEvent evt) {                                                
        xMouse = evt.getX();
        yMouse = evt.getY();
    }                                               

    private void tcBarraTituloPanelMouseDragged(java.awt.event.MouseEvent evt) {                                                
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }                                               

    private void tcCedulaTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void tcAlimentarNBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.exit(0);
    }                                        

    private void tcaAlimentarGBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void tcCrearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void tcGuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void tcEliminarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCHormigueroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCHormigueroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCHormigueroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCHormigueroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TCHormigueroFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private java.awt.Button tcAlimentarNBtn;
    private javax.swing.JPanel tcBarraTituloPanel;
    private javax.swing.JPanel tcBotonesPnl;
    private javax.swing.JLabel tcCedulaLbl;
    private javax.swing.JTextField tcCedulaTxtBox;
    private java.awt.Button tcCrearBtn1;
    private java.awt.Button tcEliminarBtn1;
    private javax.swing.JPanel tcFondoPanel;
    private javax.swing.JComboBox<String> tcGenoalimentoCB;
    private java.awt.Button tcGuardarBtn;
    private javax.swing.JPanel tcInfoPersonalPnl;
    private javax.swing.JComboBox<String> tcIngestaNativaCB;
    private javax.swing.JLabel tcLogoImgLbl;
    private javax.swing.JLabel tcNombreLbl;
    private javax.swing.JTextField tcNombreTxtBox;
    private javax.swing.JLabel tcTituloLabel;
    private java.awt.Button tcaAlimentarGBtn;
    // End of variables declaration                   
    
}
